In [1]:
#SET UP GOOGLE MAPS AND PLACES API

#CREATE HEATMAPS FOR WEATHER PARAMETERS

In [2]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [3]:
# read cities.csv file into a dataframe.

# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Taltal,CL,2022-01-05 23:07:26,-25.4000,-70.4833,67.87,76,24,5.48
1,1,Yorosso,ML,2022-01-05 23:07:26,12.3536,-4.7761,70.59,17,40,6.87
2,2,Hilo,US,2022-01-05 23:07:27,19.7297,-155.0900,80.80,75,20,9.22
3,3,Mataura,NZ,2022-01-05 23:07:27,-46.1927,168.8643,54.48,57,84,7.54
4,4,Arraial Do Cabo,BR,2022-01-05 23:07:27,-22.9661,-42.0278,76.41,87,100,9.04

In [4]:
# get the data types to check for integers or floating-point decimal numbers.

city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [5]:
##Create a Maximum Temperature Heatmap

In [6]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [7]:
# Get the maximum temperature to include positive temperatures.
max_temp = city_data_df["Max Temp"]
[max(temp, 0) for temp in max_temp]

[67.87,
 70.59,
 80.8,
 54.48,
 76.41,
 0,
 40.6,
 69.78,
 0,
 79.09,
 60.91,
 47.91,
 0,
 0,
 63.81,
 74.79,
 68.02,
 29.98,
 64.31,
 76.46,
 31.73,
 69.04,
 41.63,
 17.6,
 39.29,
 78.78,
 26.62,
 73.17,
 79.61,
 82.45,
 62.1,
 25.43,
 81.18,
 72.93,
 54.81,
 74.89,
 24.67,
 69.1,
 32.4,
 0,
 61.72,
 10.81,
 66.36,
 67.66,
 67.1,
 0,
 39.0,
 67.12,
 51.46,
 0,
 31.91,
 0,
 48.38,
 34.83,
 80.83,
 12.45,
 66.13,
 0,
 62.1,
 73.15,
 81.5,
 0,
 33.71,
 84.36,
 58.42,
 1.26,
 77.13,
 80.83,
 0,
 39.25,
 76.21,
 15.82,
 0,
 61.57,
 62.46,
 59.2,
 71.49,
 78.22,
 23.22,
 79.92,
 81.28,
 46.51,
 80.47,
 24.46,
 58.77,
 57.07,
 62.89,
 54.82,
 66.27,
 62.33,
 28.0,
 79.2,
 78.89,
 59.16,
 53.38,
 65.1,
 76.24,
 68.29,
 72.63,
 81.81,
 3.78,
 68.76,
 54.19,
 33.87,
 69.22,
 68.0,
 38.12,
 85.77,
 41.81,
 70.83,
 64.8,
 77.61,
 79.11,
 78.21,
 67.01,
 75.47,
 66.76,
 78.89,
 52.47,
 51.01,
 0,
 83.55,
 62.35,
 71.42,
 77.9,
 68.34,
 1.9,
 74.39,
 76.35,
 38.61,
 63.28,
 63.32,
 8.44,
 79.99,
 22.15,
 0,
 67.23,
 52.93,
 36.1,
 60.17,
 80.4,
 88.25,
 21.83,
 77.5,
 61.34,
 1.29,
 79.48,
 57.4,
 76.98,
 58.86,
 61.23,
 61.72,
 73.13,
 12.45,
 5.09,
 64.65,
 65.88,
 0,
 74.26,
 0,
 59.76,
 31.75,
 68.05,
 60.85,
 65.61,
 84.69,
 0,
 0,
 87.91,
 80.58,
 74.43,
 0,
 82.53,
 10.98,
 70.9,
 81.5,
 20.95,
 62.33,
 81.97,
 0,
 9.25,
 37.11,
 70.09,
 4.3,
 78.39,
 16.75,
 63.12,
 75.79,
 66.31,
 53.58,
 74.14,
 40.96,
 74.73,
 22.98,
 84.74,
 55.78,
 71.29,
 76.08,
 86.25,
 14.11,
 86.67,
 26.37,
 68.56,
 70.36,
 76.64,
 28.99,
 0,
 37.45,
 34.48,
 15.69,
 63.88,
 73.13,
 40.91,
 3.6,
 54.3,
 64.13,
 2.93,
 73.58,
 81.61,
 57.61,
 16.68,
 85.78,
 73.45,
 84.34,
 80.65,
 32.92,
 48.24,
 75.79,
 39.18,
 57.87,
 69.89,
 61.75,
 15.49,
 84.76,
 73.96,
 63.7,
 62.01,
 82.47,
 74.79,
 76.89,
 85.44,
 15.48,
 7.75,
 0,
 35.53,
 43.75,
 36.59,
 14.23,
 80.98,
 35.31,
 63.01,
 62.67,
 70.59,
 65.01,
 42.35,
 35.8,
 39.33,
 58.71,
 24.69,
 30.36,
 56.71,
 77.0,
 46.89,
 21.97,
 0,
 62.11,
 0,
 78.35,
 80.28,
 71.06,
 44.96,
 0,
 0,
 0,
 77.38,
 70.61,
 33.91,
 48.02,
 34.72,
 6.58,
 84.02,
 74.41,
 86.0,
 29.23,
 82.98,
 74.16,
 22.64,
 79.61,
 72.05,
 81.54,
 41.61,
 79.3,
 73.31,
 41.04,
 70.9,
 87.17,
 37.31,
 80.83,
 55.51,
 74.34,
 79.16,
 76.44,
 75.24,
 59.88,
 29.46,
 0,
 81.18,
 56.91,
 76.55,
 51.26,
 73.04,
 0,
 92.1,
 48.54,
 14.52,
 0,
 0,
 0,
 17.55,
 77.59,
 40.6,
 37.63,
 36.82,
 10.6,
 29.05,
 36.32,
 24.04,
 35.64,
 86.05,
 0,
 52.05,
 58.87,
 54.7,
 80.82,
 54.75,
 70.75,
 0,
 61.81,
 69.75,
 52.02,
 41.05,
 59.47,
 77.94,
 0,
 25.34,
 11.52,
 61.72,
 58.69,
 25.99,
 79.32,
 58.93,
 65.44,
 0,
 72.14,
 63.57,
 62.01,
 71.69,
 0,
 79.16,
 71.4,
 45.97,
 78.53,
 79.97,
 86.61,
 78.22,
 0,
 61.43,
 0,
 64.98,
 80.92,
 68.67,
 0,
 39.85,
 83.19,
 73.49,
 72.12,
 21.63,
 72.75,
 52.02,
 68.2,
 80.42,
 11.08,
 0,
 56.17,
 61.97,
 57.58,
 24.91,
 45.14,
 41.36,
 81.09,
 61.02,
 57.88,
 78.4,
 48.85,
 41.27,
 83.39,
 34.97,
 65.59,
 9.19,
 76.41,
 77.29,
 53.91,
 0,
 64.22,
 35.98,
 40.6,
 20.3,
 75.38,
 70.12,
 0,
 0,
 17.1,
 72.0,
 76.55,
 79.09,
 84.69,
 74.84,
 24.19,
 74.34,
 74.34,
 89.08,
 36.59,
 30.79,
 75.06,
 0,
 25.47,
 75.61,
 73.04,
 34.75,
 72.34,
 43.41,
 0,
 29.62,
 73.98,
 56.25,
 17.87,
 58.62,
 84.81,
 83.03,
 82.2,
 86.02,
 57.81,
 41.58,
 40.55,
 85.77,
 52.97,
 68.74,
 33.03,
 83.43,
 75.07,
 36.25,
 64.98,
 71.56,
 70.59,
 79.86,
 69.01,
 74.77,
 74.28,
 76.95,
 35.46,
 38.93,
 35.17,
 66.38,
 52.41,
 76.95,
 81.27,
 35.69,
 76.77,
 67.95,
 42.53,
 77.29,
 71.47,
 5.88,
 60.85,
 81.55,
 73.29,
 0,
 41.04,
 34.93,
 64.74,
 55.02,
 11.39,
 75.22,
 58.19,
 65.37,
 41.27,
 69.24,
 0,
 67.86,
 76.93,
 32.77,
 50.09,
 76.05,
 59.07,
 76.33,
 68.92,
 52.32,
 68.77,
 0,
 31.95,
 84.96,
 89.62,
 48.07,
 35.13,
 70.79,
 78.64,
 71.71,
 74.86,
 75.51,
 85.6,
 63.97,
 48.18,
 66.18,
 46.85,
 57.85,
 3.16,
 12.13,
 77.52,
 0,
 76.42,
 0,
 74.95,
 25.48,
 73.83,
 31.42,
 64.33,
 0,
 17.6,
 80.53,
 16.27,
 77.02,
 73.49,
 33.78,
 90.03,
 31.08,
 76.55,
 52.32,
 73.89,
 49.42,
 82.33,
 78.03,
 43.39,
 73.72,
 35.91,
 57.25,
 72.97,
 65.95,
 0,
 0,
 35.01,
 0,
 73.85,
 67.96,
 0,
 10.62,
 80.55,
 64.65,
 83.48,
 66.74,
 0,
 69.46,
 1.2,
 82.76,
 31.93,
 3.15,
 80.02,
 74.03,
 83.48,
 80.55,
 9.64,
 13.3,
 64.27,
 75.56,
 14.59,
 80.31,
 39.06,
 56.8,
 73.33,
 64.08,
 81.59]

In [8]:
# create a heatmap for the maximum tmeperature.

# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# add the geographic center of Earth in the form of latitude and longitude (30.0° N and 31.0° E) & add zoom level so that only one map of Earth is shown.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
##Adjust Heatmap Zoom, Intensity, and Point  ((reflected above)).

In [10]:
##Create a Percent Humidity Heatmap

In [11]:
# reuse code and use humidity values for measurements.

# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
##Create a Percent Cloudiness Heatmap

In [13]:
# reuse code and use percent cloudiness values for measurements.

# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
##Create a Wind Speed Heatmap

In [15]:
# reuse code and use wind speed values for measurements.

# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [16]:
#GET VACATION CRITERIA

In [17]:
# write input statements for user to enter a min & max temp value, then convet to float decimal.

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [18]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
2,2,Hilo,US,2022-01-05 23:07:27,19.7297,-155.0900,80.80,75,20,9.22
4,4,Arraial Do Cabo,BR,2022-01-05 23:07:27,-22.9661,-42.0278,76.41,87,100,9.04
9,9,Cayenne,GF,2022-01-05 23:07:28,4.9333,-52.3333,79.09,88,75,3.00
19,19,Vallenar,CL,2022-01-05 23:07:31,-28.5708,-70.7581,76.46,49,0,7.63
25,25,Atuona,PF,2022-01-05 23:07:33,-9.8000,-139.0333,78.78,71,80,15.01
28,28,Cabo San Lucas,MX,2022-01-05 23:05:02,22.8909,-109.9124,79.61,58,1,3.00
29,29,Avarua,CK,2022-01-05 23:07:33,-21.2078,-159.7750,82.45,78,20,4.61
32,32,Sorong,ID,2022-01-05 23:07:34,-0.8833,131.2500,81.18,74,71,4.34
54,54,Vaitape,PF,2022-01-05 23:08:39,-16.5167,-151.7500,80.83,70,3,2.75
60,60,Eydhafushi,MV,2022-01-05 23:08:41,5.1033,73.0708,81.50,76,88,12.41

In [19]:
# use count() on preferred city dataframe to determine if it has any null values.

preferred_cities_df.count()

City_ID       141
City          141
Country       141
Date          141
Lat           141
Lng           141
Max Temp      141
Humidity      141
Cloudiness    141
Wind Speed    141
dtype: int64

In [20]:
#MAP VACATION CRITERIA

In [21]:
##Get Travel Destinations

# create a new DataFrame specifically for the data needed to create a heatmap and pop-up markers.
# make a copy of dataframe with adjustments to columns

In [22]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

               City Country  Max Temp      Lat       Lng Hotel Name
2              Hilo      US     80.80  19.7297 -155.0900
4   Arraial Do Cabo      BR     76.41 -22.9661  -42.0278
9           Cayenne      GF     79.09   4.9333  -52.3333
19         Vallenar      CL     76.46 -28.5708  -70.7581
25           Atuona      PF     78.78  -9.8000 -139.0333
28   Cabo San Lucas      MX     79.61  22.8909 -109.9124
29           Avarua      CK     82.45 -21.2078 -159.7750
32           Sorong      ID     81.18  -0.8833  131.2500
54          Vaitape      PF     80.83 -16.5167 -151.7500
60       Eydhafushi      MV     81.50   5.1033   73.0708

In [23]:
##Retrieve Hotels from a Nearby Search

##Set the Parameters for a Nearby Search

In [24]:
# add the parameters as key-value pairs. Add the params dictionary, API key, type, and radius parameters.

# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [25]:
##Practice Using a Fixed Latitude and Longitude
# ((switching to google_nearby_search.ipynb file))

In [26]:
##Iterate Through hotel_df DataFrame

In [27]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

IndexError: list index out of range

In [30]:
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
2,Hilo,US,80.80,19.7297,-155.0900,Hilo Hawaiian Hotel
4,Arraial Do Cabo,BR,76.41,-22.9661,-42.0278,Pousada Porto Praia
9,Cayenne,GF,79.09,4.9333,-52.3333,Hôtel Le Dronmi
19,Vallenar,CL,76.46,-28.5708,-70.7581,Humacao Bed & Breakfast
25,Atuona,PF,78.78,-9.8000,-139.0333,Villa Enata
28,Cabo San Lucas,MX,79.61,22.8909,-109.9124,Hotel Tesoro Los Cabos
29,Avarua,CK,82.45,-21.2078,-159.7750,Paradise Inn
32,Sorong,ID,81.18,-0.8833,131.2500,Waigo Splash Hotel
54,Vaitape,PF,80.83,-16.5167,-151.7500,Conrad Bora Bora Nui
60,Eydhafushi,MV,81.50,5.1033,73.0708,Soneva Fushi

In [31]:
##Create a Maximum Temperature Heatmap from a Hotel DataFrame

In [32]:
# create a heatmap using the max temp from our hotel_df DataFrame by reusing the code and changing the DataFrame name.

# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [33]:
# add the markers for each city on top of the heatmap. 

# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [34]:
# add a pop-up marker for each city that displays the hotel name, city name, country, and maximum temperature.

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [35]:
# add data to the code by iterating through dataframe w/ iterrows() funct
# then add info to gmaps.marker_layer()

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [36]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))